name: dartframe
description: DartFrame is a Dart library inspired by Pandas, simplifying structured data handling (tables, CSVs, JSON) with function tools for filtering, transforming, and analysis.
version: 0.7.0
repository: https://github.com/gameticharles/DartFrame

environment:
  sdk: ^3.6.0

documentation: "https://github.com/gameticharles/DartFrame/blob/main/doc/dataframe.md"

# Add regular dependencies here.
dependencies:
  archive: ^3.6.1
  intl: ^0.20.2
  web: ^1.1.1
  r_tree: ^3.0.1
  excel: ^4.0.6
  csv: ^6.0.0

dev_dependencies:
  benchmark_harness: ^2.3.1
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - dataframe
  - series
